Base restructure of wrapper to support --help command at all times
Earlier versions of the wrapper required all the various dependencies and environments to be created before a command such as -h/--help could be executed. This commit is the first version in which this should be solved

diff --git a/jovian b/jovian
--- a/jovian
+++ b/jovian
@@ -6,8 +6,16 @@
 VERSION="0.9.0"
 INSTALL_LOG="jovian_installation_log.txt"
 
-#Default INPUT_DIR
+#Default values
 INPUT_DIR="raw_data/"
+JOVIAN_HELP="FALSE"
+SNAKEMAKE_HELP="FALSE"
+INSTALL_CONDA="FALSE"
+INSTALL_IGVJS="FALSE"
+INSTALL_DB="FALSE"
+CLEAN="FALSE"
+SHEET_SUCCESS="FALSE"
+
 
 ###### TO-DO'S
 # read-length code van Anita
@@ -35,6 +43,96 @@ next
 next
 
 
+### Parse the jovian commandline arguments, if they are not part of jovian, they get send to Snakemake
+POSITIONAL=()
+while [[ $# -gt 0 ]]
+do
+    key="$1"
+    case $key in
+        -i|--input)
+        INPUT_DIR="$2"
+        shift # Next
+        shift # Next
+        ;;
+        -h|--help)
+        JOVIAN_HELP="TRUE"
+        shift # Next
+        ;;
+        -sh|--snakemake-help)
+        SNAKEMAKE_HELP="TRUE"
+        shift # Next
+        ;;
+        -ic|--install-dependencies)
+        INSTALL_CONDA="TRUE"
+        shift # Next
+        ;;
+        -ii|--install-igvjs)
+        INSTALL_IGVJS="TRUE"
+        shift # Next
+        ;;
+        -id|--install-databases)
+        INSTALL_DB="TRUE"
+        shift # Next
+        ;;
+        --clean)
+        CLEAN="TRUE"
+        shift # Next
+        ;;
+        *) # Any other option
+        POSITIONAL+=("$1") # save in array
+        shift # Next
+        ;;
+    esac
+done
+set -- "${POSITIONAL[@]:-}" # Restores the positional arguments (i.e. without the case arguments above) which then can be called via `$@` or `$[0-9]` etc. These parameters are send to Snakemake.
+
+### Check the jovian CLI arguments and do stuff
+if [ "${CLEAN:-}" == "TRUE" ]; then
+    echo -e "The following files and folders will be deleted:\ndata/\nlogs/\nresults/\nsample_sheet.yaml\n\n"
+    read -r -p "Are you sure you wish to permanently delete these files and folders? [y/N] " response
+    response=${response,,}
+    if [[ "$response" =~ ^(yes|y)$ ]]; then
+        echo -e "Removing Jovian output: data/ logs/ results/ sample_sheet.yaml"
+        rm -rf data/
+        rm -rf logs/
+        rm -rf results/
+        rm sample_sheet.yaml
+    fi
+    exit 0
+fi
+if [ "${JOVIAN_HELP:-}" == "TRUE" ]; then # Print Jovian help message
+    cat <<HELP_USAGE
+Jovian, version $VERSION, built with Snakemake
+  Usage: bash $0 -i <INPUT_DIR> <arguments>
+Input:
+  --input -i DIR               This is the folder containing your input fastq files.
+                               N.B. pathing must be relative from current directory.
+                               N.B. It is only designed for Illumina paired-end data.
+Output:
+  data/                        Contains detailed intermediate files
+  logs/                        Contains all log files
+  results/                     Contains all final results, these are visualized via the
+                               web-report (Notebook_report.ipynb)
+Parameters:
+  --help -h                    Print the Jovian help document
+  --snakemake-help -sh         Print the Snakemake help document
+  --clean                      Removes Jovian output
+  --keep-going -k              Useful snakemake command: Go on with independent jobs if
+                               a job fails.
+  --dry-run -n                 Useful snakemake command: Do not execute anything, and
+                               display what would be done.
+  --unlock                     Useful snakemake command: Remove a lock on the working
+                               directory.
+  --quiet -q                   Useful snakemake command: Do not output any progress or
+                               rule information.
+Installation:
+  --install-dependencies -ic   Install the required software dependencies
+  --install-igvjs -ii          Install IGVjs dependency
+  --install-databases -id      Install required databases
+HELP_USAGE
+    exit 0
+fi
+
 ### Pre-flight check: Assess availability of required files, conda and Jovian_master environment
 
 PATH_JOVIAN_MASTER_YAML="envs/Jovian_master_environment.yaml"
@@ -51,9 +149,6 @@ elif [ ! -e "$PATH_JOVIAN_HELPER_YAML" ]; then # If this yaml file does not exis
     exit 1
 elif [ ! -e "${PROFILE}/config.yaml" ]; then # If this profile folder containing config.yaml does not exist, give error.
     echo -e "ERROR: Missing file \"${PROFILE}/config.yaml\""
-    exit 1
-elif [ ! -e "${HOME}/.ncbirc" ]; then # If the BLAST required ~/.ncbirc does not exist, give error.
-    echo -e "ERROR: Missing file \"~/.ncbirc\". \nThis is config file is required for BLAST to function, contains the locations to the BLAST databases on your local system. It should be in your home directory."
     exit 1
 elif ! command -v conda > /dev/null; then # Check if conda is not installed (i.e. the `conda` command is not available), if true, install it in ~/tmp. Otherwise, proceed.
 
@@ -125,107 +220,7 @@ if [[ $PATH != *$MASTER_NAME* ]]; then # If the master environment is not in you
     set -ue # Turn bash strict mode on again
     echo -e "Succesfully activated Jovian_master environment"
 fi
-
-### Parse the jovian commandline arguments, if they are not part of jovian, they get send to Snakemake
-POSITIONAL=()
-while [[ $# -gt 0 ]]
-do
-    key="$1"
-    case $key in
-        -i|--input)
-        INPUT_DIR="$2"
-        shift # Next
-        shift # Next
-        ;;
-        -h|--help)
-        JOVIAN_HELP="TRUE"
-        shift # Next
-        ;;
-        -sh|--snakemake-help)
-        SNAKEMAKE_HELP="TRUE"
-        shift # Next
-        ;;
-        -ic|--install-dependencies)
-        INSTALL_CONDA="TRUE"
-        shift # Next
-        ;;
-        -ii|--install-igvjs)
-        INSTALL_IGVJS="TRUE"
-        shift # Next
-        ;;
-        -id|--install-databases)
-        INSTALL_DB="TRUE"
-        shift # Next
-        ;;
-        --clean)
-        CLEAN="TRUE"
-        shift # Next
-        ;;
-        *) # Any other option
-        POSITIONAL+=("$1") # save in array
-        shift # Next
-        ;;
-    esac
-done
-set -- "${POSITIONAL[@]:-}" # Restores the positional arguments (i.e. without the case arguments above) which then can be called via `$@` or `$[0-9]` etc. These parameters are send to Snakemake.
-
-### Check the jovian CLI arguments and do stuff
-if [ "${CLEAN:-}" == "TRUE" ]; then
-    echo -e "The following files and folders will be deleted:\ndata/\nlogs/\nresults/\nsample_sheet.yaml\n\n"
-    read -r -p "Are you sure you wish to permanently delete these files and folders? [y/N] " response
-    response=${response,,}
-    if [[ "$response" =~ ^(yes|y)$ ]]; then
-        echo -e "Removing Jovian output: data/ logs/ results/ sample_sheet.yaml"
-        rm -rf data/
-        rm -rf logs/
-        rm -rf results/
-        rm sample_sheet.yaml
-    fi
-    exit 0
-elif [ "${JOVIAN_HELP:-}" == "TRUE" ]; then # Print Jovian help message
-    cat <<HELP_USAGE
-Jovian, version $VERSION, built with Snakemake
-  Usage: bash $0 -i <INPUT_DIR> <arguments>
-Input:
-  --input -i DIR               This is the folder containing your input fastq files.
-                               N.B. pathing must be relative from current directory.
-                               N.B. It is only designed for Illumina paired-end data.
-Output:
-  data/                        Contains detailed intermediate files
-  logs/                        Contains all log files
-  results/                     Contains all final results, these are visualized via the
-                               web-report (Notebook_report.ipynb)
-Parameters:
-  --help -h                    Print the Jovian help document
-  --snakemake-help -sh         Print the Snakemake help document
-  --clean                      Removes Jovian output
-  --keep-going -k              Useful snakemake command: Go on with independent jobs if
-                               a job fails.
-  --dry-run -n                 Useful snakemake command: Do not execute anything, and
-                               display what would be done.
-  --unlock                     Useful snakemake command: Remove a lock on the working
-                               directory.
-  --quiet -q                   Useful snakemake command: Do not output any progress or
-                               rule information.
-Installation:
-  --install-dependencies -ic   Install the required software dependencies
-  --install-igvjs -ii          Install IGVjs dependency
-  --install-databases -id      Install required databases
-HELP_USAGE
-    exit 0
-elif [ "${SNAKEMAKE_HELP:-}" == "TRUE" ]; then
-    snakemake --help
-    exit 0
-elif [ "${INSTALL_CONDA:-}" == "TRUE" ]; then
-    echo -e "\nInstalling required conda environments, this can take up to an hour..."
-    snakemake --use-conda --create-envs-only --profile $PROFILE
-    exit 0
-elif [ "${INSTALL_IGVJS:-}" == "TRUE" ]; then
-    echo -e "Installing IGVjs software, this can take up to 15 minutes..."
-    bash bin/install_IGVjs.sh
-    echo -e "DONE"
-    exit 0
-elif [ "${INSTALL_DB:-}" == "TRUE" ]; then
+if [ "${INSTALL_DB:-}" == "TRUE" ]; then
     echo -e "Installing databases, this can take hours for a fresh installation..."
     if [[ $PATH != *$HELPER_NAME* ]]; then # If helper env is not in your path (i.e. it is not currently active), do...
         set +ue # Turn bash strict mode off because that breaks conda
@@ -244,6 +239,28 @@ elif [ "${INSTALL_DB:-}" == "TRUE" ]; then
     exit 0
 fi
 
+if [ "${SNAKEMAKE_HELP:-}" == "TRUE" ]; then
+    snakemake --help
+    exit 0
+fi
+
+if [ "${INSTALL_CONDA:-}" == "TRUE" ]; then
+    echo -e "\nInstalling required conda environments, this can take up to an hour..."
+    snakemake --use-conda --create-envs-only --profile $PROFILE
+    exit 0
+fi
+if [ "${INSTALL_IGVJS:-}" == "TRUE" ]; then
+    echo -e "Installing IGVjs software, this can take up to 15 minutes..."
+    bash bin/install_IGVjs.sh
+    echo -e "DONE"
+    exit 0
+fi
+
+if [ ! -e "${HOME}/.ncbirc" ]; then # If the BLAST required ~/.ncbirc does not exist, give error.
+    echo -e "ERROR: Missing file \"~/.ncbirc\". \nThis is config file is required for BLAST to function, contains the locations to the BLAST databases on your local system. It should be in your home directory."
+    exit 1
+fi
+
 ### Pass other CLI arguments along to Snakemake
 if [ ! -d ${INPUT_DIR} ]; then
     echo -e "The input directory specified (${INPUT_DIR}) does not exist"
@@ -251,7 +268,6 @@ if [ ! -d ${INPUT_DIR} ]; then
     exit 1
 fi
 
-SHEET_SUCCESS="FALSE"
 ZIPFILES=(${INPUT_DIR}*.gz)
 FASTQFILES=(${INPUT_DIR}*.fastq)
 FQFILES=(${INPUT_DIR}*.fq)
