while loops in installer + test for archive speed

diff --git a/jovian b/jovian
--- a/jovian
+++ b/jovian
@@ -1,10 +1,10 @@
 #!/bin/bash
+# shellcheck disable=SC1091
 #set -euo pipefail
 #set -v
 #set -x
 
 #load in functions
-# shellcheck disable=SC1091
 source bin/functions.sh
 eval "$(parse_yaml profile/pipeline_parameters.yaml "params_")"
 eval "$(parse_yaml profile/config.yaml "configuration_")"
@@ -16,7 +16,8 @@ PROFILE="profile"
 
 UNIQUE_ID=$(bin/generate_id.sh)
 SET_HOSTNAME=$(bin/gethostname.sh)
-AVAILABLE_CORES=$(grep -c ^processor /proc/cpuinfo)
+SYSTEM_CORES=$(grep -c ^processor /proc/cpuinfo)
+AVAILABLE_CORES=$(expr ${SYSTEM_CORES} - 2)
 IGVJS_LOCATION="bin/software/igv.js/dist/igv.min.js"
 
 ### Jovian Conda environment names
@@ -162,16 +163,25 @@ if [ "${CLEAN:-}" == "TRUE" ]; then
     line
     spacer
     echo -e "The following files and folders will be deleted:\ndata/\nlogs/\nresults/\nprofile/variables.yaml\nsample_sheet.yaml\n\n"
-    read -r -p "Are you sure you wish to permanently delete these files and folders? [y/N] " response
-    response=${response,,}
-    if [[ "${response}" =~ ^(yes|y)$ ]]; then
-        echo -e "Removing Jovian output: data/ logs/ results/ profile/variables.yaml sample_sheet.yaml"
-        rm -rf data/
-        rm -rf logs/
-        rm -rf results/
-        rm sample_sheet.yaml
-        rm profile/variables.yaml
-    fi
+    while read -r -p "Are you sure you wish to permanently delete these files and folders? [y/N] " response
+    do
+        response=${response,,}
+        if [[ "${response}" =~ ^(yes|y)$ ]]; then
+            echo -e "Removing Jovian output: data/ logs/ results/ profile/variables.yaml sample_sheet.yaml"
+            rm -rf data/
+            rm -rf logs/
+            rm -rf results/
+            rm sample_sheet.yaml
+            rm profile/variables.yaml
+            break
+        elif [[ "${response}" =~ ^(no|n)$ ]]; then
+            echo -e "Aborting cleaning process on user request"
+            exit 0
+        else
+            echo -e "Please answer with 'yes' or 'no'"
+            minispacer
+        fi
+    done
     exit 0
 fi
 
@@ -244,75 +254,6 @@ HELP_USAGE
     exit 0
 fi
 
-### Archiving of relevant data in a single tar.gz file
-if [ "${ARCHIVE:-}" == "TRUE" ]; then
-    line
-    spacer
-    echo -e "\n\nArchiving the Jovian data and results can take several hours depending on the size of your dataset(s)."
-    echo -e "This archiving process will NOT include the raw dataset in the final archive"
-    echo -e "\nIt is advised to run the archiving process overnight, it is strongly advised to not stop the process once you started it"
-    read -r -p "Do you want to start the Jovian archiving process now? [y/N] " archive_answer
-    archive_answer=${archive_answer,,}
-    if [[ "${archive_answer}" =~ ^(yes|y)$ ]]; then
-        echo -e "\n\nStarting the archiving process\n\n"
-        eval "$(parse_yaml profile/variables.yaml "config_")"
-        
-        if [ -e data/ ]; then
-            echo -e "Found the 'data/' folder, appending to archive..."
-            (tar --append --file=archive_"${config_Jovian_run_identifier}"_jovian-"${VERSION}".tar data/) &
-            spinner
-        else
-            echo -e "Couldn't find the 'data/' folder in this working directory, skipping this folder in archiving"
-        fi
-
-        if [ -e logs/ ]; then
-            echo -e "Found the 'logs/' folder, appending to archive..."
-            (tar --append --file=archive_"${config_Jovian_run_identifier}"_jovian-"${VERSION}".tar logs/) &
-            spinner
-        else
-            echo -e "Couldn't find the 'logs/' folder in this working directory, skipping this folder in archiving"
-        fi
-        
-        if [ -e results/ ]; then
-            echo -e "Found the 'results/' folder, appending to archive..."
-            (tar --append --file=archive_"${config_Jovian_run_identifier}"_jovian-"${VERSION}".tar results/) &
-            spinner
-        else
-            echo -e "Couldn't find the 'results/' folder in this working directory, skipping this folder in archiving"
-        fi
-        
-        if [ -e sample_sheet.yaml ]; then
-            echo -e "Found 'sample_sheet.yaml', appending to archive..."
-            (tar --append --file=archive_"${config_Jovian_run_identifier}"_jovian-"${VERSION}".tar sample_sheet.yaml) &
-            spinner
-        else
-            echo -e "Couldn't find the file 'sample_sheet.yaml' in this working directory, skipping this file in archiving"
-        fi
-        
-        if [ -e profile/ ]; then
-            echo -e "Found 'profile' folder, appending to archive..."
-            (tar --append --file=archive_"${config_Jovian_run_identifier}"_jovian-"${VERSION}".tar profile/) &
-            spinner
-        else
-            echo -e "Couldn't find the 'profile' folder in this working directory, skipping this file in archiving"
-        fi
-
-        if [ -e archive_"${config_Jovian_run_identifier}"_jovian-"${VERSION}".tar ]; then
-            echo -e "\n\nFiles and folders have been appended to the archive."
-            echo -e "Compressing archive..."
-            (gzip archive_"${config_Jovian_run_identifier}"_jovian-"${VERSION}".tar) &
-            spinner
-        else
-            echo "No files and folders could be found for archiving."
-            exit 1
-        fi
-    else
-        echo -e "Aborting the archiving process..."
-        exit 0
-    fi
-exit 0
-fi
-
 ###############################################################################################################
 ##### Installation block                                                                                  #####
 ###############################################################################################################
@@ -348,44 +289,56 @@ if ! command -v conda > /dev/null; then # Check if conda is not installed (i.e. 
         ### confirmation of conda installation
         installer_intro
         echo -e "Miniconda missing. Installing Miniconda can take up to 15 minutes..."
-        read -r -p "Do you wish to install (mini)conda now? [y/N] " response
-        response=${response,,}
-        if [[ "${response}" =~ ^(yes|y)$ ]]; then
-            echo "Jovian ${VERSION}" > ${INSTALL_LOG}
-            line | tee -a ${INSTALL_LOG}
-            curl -o latest.sh -L https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
-            chmod +x latest.sh
-            sh latest.sh -b -p "${HOME}/tmp/Miniconda3" | tee -a ${INSTALL_LOG}
-            rm latest.sh
-            tput reset
-            installer_intro
-        else
-            echo -e "Conda is a requirement for Jovian to run."
-            echo -e "Exiting because conda isn't installed and automatic installation of conda was declined by user"
-            exit 1
-        fi
+        while read -r -p "Do you wish to install (mini)conda now? [y/N] " response
+        do
+            response=${response,,}
+            if [[ "${response}" =~ ^(no|n) ]]; then
+                minispacer
+                echo -e "Conda is a requirement for Jovian to run."
+                echo -e "Exiting because conda isn't installed and automatic installation of conda was declined by user"
+                exit 1
+            elif [[ "${response}" =~ ^(yes|y)$ ]]; then
+                echo "Jovian ${VERSION}" > ${INSTALL_LOG}
+                line | tee -a ${INSTALL_LOG}
+                curl -o latest.sh -L https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
+                chmod +x latest.sh
+                sh latest.sh -b -p "${HOME}/tmp/Miniconda3" | tee -a ${INSTALL_LOG}
+                rm latest.sh
+                tput reset
+                installer_intro
+                break
+            else
+                echo -e "Please answer with 'yes' or 'no'"
+                minispacer
+            fi
+        done
         
         ### conda has been installed by previous step, confirm addition to PATH
         echo -e "Conda is installed but not yet added to PATH, do you wish to add conda to your PATH?"
-        read -r -p "The conda PATH will be added to your ~/.bashrc and will only affect you. [y/N] " answer
-        answer=${answer,,}
-        if [[ "${answer}" =~ ^(yes|y)$ ]]; then
-            echo "PATH=$PATH:${HOME}/tmp/Miniconda3/bin" >> "${HOME}/.bashrc" | tee -a ${INSTALL_LOG}
-            source "${HOME}"/.bashrc | tee -a ${INSTALL_LOG}
-            export PATH=${HOME}/tmp/Miniconda3/bin:$PATH
-            tput reset
-            line
-            installer_intro
-            echo -e "Conda succesfully added to PATH"
-        else
-            export PATH=${HOME}/tmp/Miniconda3/bin:$PATH | tee -a ${INSTALL_LOG}
-            tput reset
-            line
-            installer_intro
-            line
-            spacer
-            echo -e "Conda has not been permanently added to PATH, this means you cannot use the conda command once this session closes."
-        fi
+        while read -r -p "The conda PATH will be added to your ~/.bashrc and will only affect you. [y/N] " answer
+        do
+            answer=${answer,,}
+            if [[ "${answer}" =~ ^(yes|y)$ ]]; then
+                echo "PATH=$PATH:${HOME}/tmp/Miniconda3/bin" >> "${HOME}/.bashrc" | tee -a ${INSTALL_LOG}
+                source "${HOME}"/.bashrc | tee -a ${INSTALL_LOG}
+                export PATH=${HOME}/tmp/Miniconda3/bin:$PATH
+                tput reset
+                line
+                installer_intro
+                echo -e "Conda succesfully added to PATH"
+            elif [[ "${answer}" =~ ^(no|n)$ ]]; then
+                export PATH=${HOME}/tmp/Miniconda3/bin:$PATH | tee -a ${INSTALL_LOG}
+                tput reset
+                line
+                installer_intro
+                line
+                spacer
+                echo -e "Conda has not been permanently added to PATH, this means you cannot use the conda command once this session closes."
+            else
+                echo -e "Please answer with 'yes' or 'no'"
+                minispacer
+            fi
+        done
     
         echo -e "\n"
         echo -e "Installation of Conda is done"
@@ -413,17 +366,22 @@ if [[ $PATH != *${MASTER_NAME}* ]]; then # If the master environment is not in y
     if [ ! $? -eq 0 ]; then # If exit statement is not 0, i.e. master conda env hasn't been installed yet, do...
         installer_intro
 
-        read -r -p "The Jovian_master environment hasn't been installed yet, do you want to install this environment now? [y/N] " envanswer
-        envanswer=${envanswer,,}
-        if [[ "${envanswer}" =~ ^(yes|y)$ ]]; then
-            echo -e "\tInstalling Jovian master environment..." | tee -a ${INSTALL_LOG}   
-            conda env create -f ${PATH_JOVIAN_MASTER_YAML} | tee -a ${INSTALL_LOG} # Create the env from the specified yaml file
-            source activate "${MASTER_NAME}"
-            echo -e "DONE"
-        else
-            echo -e "The Jovian_master environment is a requirement. Exiting because Jovian cannot continue without this environment"
-            exit 1
-        fi
+        while read -r -p "The Jovian_master environment hasn't been installed yet, do you want to install this environment now? [y/N] " envanswer
+        do
+            envanswer=${envanswer,,}
+            if [[ "${envanswer}" =~ ^(yes|y)$ ]]; then
+                echo -e "\tInstalling Jovian master environment..." | tee -a ${INSTALL_LOG}   
+                conda env create -f ${PATH_JOVIAN_MASTER_YAML} | tee -a ${INSTALL_LOG} # Create the env from the specified yaml file
+                source activate "${MASTER_NAME}"
+                echo -e "DONE"
+            elif [[ "${envanswer}" =~ ^(no|n)$ ]]; then
+                echo -e "The Jovian_master environment is a requirement. Exiting because Jovian cannot continue without this environment"
+                exit 1
+            else
+                echo -e "Please answer with 'yes' or 'no'"
+                minispacer
+            fi
+        done
     fi
     set -ue # Turn bash strict mode on again
     echo -e "Succesfully activated Jovian_master environment"
@@ -432,6 +390,81 @@ fi
         ###############################################################################################################
         ##### From this point onwards you can safely assume Conda is installed and Jovian_master is activated     #####
         ###############################################################################################################
+
+### Archiving of relevant data in a single tar.gz file
+if [ "${ARCHIVE:-}" == "TRUE" ]; then
+    line
+    spacer
+    echo -e "\n\nArchiving the Jovian data and results can take several hours depending on the size of your dataset(s)."
+    echo -e "This archiving process will NOT include the raw dataset in the final archive"
+    echo -e "\nIt is advised to run the archiving process overnight, it is strongly advised to not stop the process once you started it"
+    while read -r -p "Do you want to start the Jovian archiving process now? [y/N] " archive_answer
+    do
+    archive_answer=${archive_answer,,}
+        if [[ "${archive_answer}" =~ ^(yes|y)$ ]]; then
+            echo -e "\n\nStarting the archiving process\n\n"
+            eval "$(parse_yaml profile/variables.yaml "config_")"
+            
+            if [ -e data/ ]; then
+                echo -e "Found the 'data/' folder, appending to archive..."
+                (tar --append --file=archive_"${config_Jovian_run_identifier}"_jovian-"${VERSION}".tar data/) &
+                spinner
+            else
+                echo -e "Couldn't find the 'data/' folder in this working directory, skipping this folder in archiving"
+            fi
+
+            if [ -e logs/ ]; then
+                echo -e "Found the 'logs/' folder, appending to archive..."
+                (tar --append --file=archive_"${config_Jovian_run_identifier}"_jovian-"${VERSION}".tar logs/) &
+                spinner
+            else
+                echo -e "Couldn't find the 'logs/' folder in this working directory, skipping this folder in archiving"
+            fi
+            
+            if [ -e results/ ]; then
+                echo -e "Found the 'results/' folder, appending to archive..."
+                (tar --append --file=archive_"${config_Jovian_run_identifier}"_jovian-"${VERSION}".tar results/) &
+                spinner
+            else
+                echo -e "Couldn't find the 'results/' folder in this working directory, skipping this folder in archiving"
+            fi
+            
+            if [ -e sample_sheet.yaml ]; then
+                echo -e "Found 'sample_sheet.yaml', appending to archive..."
+                (tar --append --file=archive_"${config_Jovian_run_identifier}"_jovian-"${VERSION}".tar sample_sheet.yaml) &
+                spinner
+            else
+                echo -e "Couldn't find the file 'sample_sheet.yaml' in this working directory, skipping this file in archiving"
+            fi
+            
+            if [ -e profile/ ]; then
+                echo -e "Found 'profile' folder, appending to archive..."
+                (tar --append --file=archive_"${config_Jovian_run_identifier}"_jovian-"${VERSION}".tar profile/) &
+                spinner
+            else
+                echo -e "Couldn't find the 'profile' folder in this working directory, skipping this file in archiving"
+            fi
+
+            if [ -e archive_"${config_Jovian_run_identifier}"_jovian-"${VERSION}".tar ]; then
+                echo -e "\n\nFiles and folders have been appended to the archive."
+                echo -e "Compressing archive..."
+                (pigz -p "${AVAILABLE_CORES}" archive_"${config_Jovian_run_identifier}"_jovian-"${VERSION}".tar) &
+                spinner
+            else
+                echo "No files and folders could be found for archiving."
+                exit 1
+            fi
+            break
+        elif [[ "${archive_answer}" =~ ^(no|n)$ ]]; then
+            echo -e "Aborting the archiving process on user request"
+            exit 0
+        else
+            echo -e "Please answer with 'yes'' or 'no'"
+            minispacer
+        fi
+    done
+exit 0
+fi
 
 ### Checker for if IGVjs is installed, otherwise, ask user if it should be installed
 if [ "$igvjs_installeranswers_igvjs" == "U" ]; then
@@ -504,8 +537,8 @@ if [ "${REBUILD_ARCHIVE}" == "TRUE" ]; then
         exit 0
     fi
 fi
+
 ### Install databases, as specified via CLI argument '-id'
-# Work-in-progress, not finished yet
 if [ "${INSTALL_DB:-}" == "TRUE" ]; then
     spacer
     line
