Fix issues for conda installer (again).

diff --git a/bin/includes/Install_miniconda b/bin/includes/Install_miniconda
--- a/bin/includes/Install_miniconda
+++ b/bin/includes/Install_miniconda
@@ -1,8 +1,9 @@
 #!/bin/bash
 # shellcheck disable=SC1091
 
-if ! command -v conda > /dev/null; then # Check if conda is not installed (i.e. the `conda` command is not available), if true, install it in ~/tmp. Otherwise, proceed.
-    if [ ! -e "${HOME}/tmp/Miniconda3" ]; then
+
+if ! command -v conda > /dev/null; then # Check if conda is not installed (i.e. the `conda` command is not available), if true, install it in ~/UserBinaries. Otherwise, proceed.
+    if [ ! -e "${HOME}/UserBinaries/Miniconda3" ]; then
         ### confirmation of conda installation
         installer_intro
         echo -e "Miniconda missing. Installing Miniconda can take up to 15 minutes..."
@@ -11,7 +12,8 @@ if ! command -v conda > /dev/null; then # Check if conda is not installed (i.e. 
             line | tee -a ${INSTALL_LOG}
             curl -o latest.sh -L https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
             chmod +x latest.sh
-            sh latest.sh -b -p "${HOME}/tmp/Miniconda3" | tee -a ${INSTALL_LOG}
+            sh latest.sh -b -p "${HOME}/UserBinaries/Miniconda3" | tee -a ${INSTALL_LOG}
+            export PATH=${HOME}/UserBinaries/Miniconda3/bin:$PATH
             rm latest.sh
             tput reset
             installer_intro
@@ -29,7 +31,8 @@ if ! command -v conda > /dev/null; then # Check if conda is not installed (i.e. 
                     line | tee -a ${INSTALL_LOG}
                     curl -o latest.sh -L https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
                     chmod +x latest.sh
-                    sh latest.sh -b -p "${HOME}/tmp/Miniconda3" | tee -a ${INSTALL_LOG}
+                    sh latest.sh -b -p "${HOME}/UserBinaries/Miniconda3" | tee -a ${INSTALL_LOG}
+                    export PATH=${HOME}/UserBinaries/Miniconda3/bin:$PATH
                     rm latest.sh
                     tput reset
                     installer_intro
@@ -40,29 +43,47 @@ if ! command -v conda > /dev/null; then # Check if conda is not installed (i.e. 
                 fi
             done
         fi
+fi
 
-    touch "${HOME}"/.jovianrc
+
+conda_loc=$(which conda)
+rcfile=~/.jovianrc
+
+if [ -f "$rcfile" ]; then
+    exit
+fi
+
+
+
+if [ -z "$conda_loc" ]; then
+    #* conda location is unknown by "which"
+        #* this means that conda wasn't installed before and probably has been installed now, 
+        #* unless this has been aborted by the user
+
+    if [ -e "${HOME}/UserBinaries/Miniconda3" ]; then
+        #? The folder structure exists which indicates that Jovian has installed Conda for the user.
+            #? Use this location for the >jovianrc< content
+        
+            touch "${HOME}"/.jovianrc
     cat << EOF >> "${HOME}"/.jovianrc
-__conda_setup="$('${HOME}/tmp/Miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
+__conda_setup="$('${HOME}/UserBinaries/Miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
 if [ $? -eq 0 ]; then
     eval "$__conda_setup"
 else
-    if [ -f "${HOME}/tmp/Miniconda3/etc/profile.d/conda.sh" ]; then
-        . "${HOME}/tmp/Miniconda3/etc/profile.d/conda.sh"
+    if [ -f "${HOME}/UserBinaries/Miniconda3/etc/profile.d/conda.sh" ]; then
+        . "${HOME}/UserBinaries/Miniconda3/etc/profile.d/conda.sh"
     else
-        export PATH="${HOME}/tmp/Miniconda3/bin:$PATH"
+        export PATH="${HOME}/UserBinaries/Miniconda3/bin:$PATH"
     fi
 fi
 unset __conda_setup
-
 export -f conda
 export -f __conda_activate
 export -f __conda_reactivate
 export -f __conda_hashr
 export -f __add_sys_prefix_to_path
-
 EOF
-    
+
         echo -e "\n"
         echo -e "Installation of Conda is done"
         echo -e "If you wish to use conda then it might be necessary to restart your terminal session"
@@ -76,8 +97,49 @@ EOF
         installer_intro
         line
         spacer
+
+
+    else
+        #! The location of conda is unknown AND the folder structure doesn't exist...
+            #! This most likely means that something went very wrong and the user must debug themselves
+            #! Manual installation of conda will be necessary
+    
+        echo -e "\n\n"
+        echo -e "Something went wrong"
+        echo -e "We were unable to find conda on your system, and we couldn't succesfully install it for you\n"
+        echo -e "Please install (mini)Conda manually on your system before continuing. (or ask your system admin to do it)"
+        exit 1
     fi
-    if [ -e "${HOME}/tmp/Miniconda3" ]; then
-        export PATH=${HOME}/tmp/Miniconda3/bin:$PATH
-    fi 
+
+
+else
+    #* Conda location IS known by "which"
+        #* Meaning that our installation block was skipped
+        #* This can be because of two things
+            #> Conda was already installed on the system
+            #> Conda was previously installed by Jovian on the system.
+
+        #@ # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
+        #@ 
+        #@ Because the conda location is known, we will assume that we dont 
+        #@ have to make sure the core concepts of conda are functional.
+        #@ 
+        #@ Instead, we will only write the basic exports to the ~/.jovianrc file that
+        #@ make sure the command "conda activate <x>" actually works.
+        #@ 
+        #@ We will source the ~/.jovianrc file in the main wrapper so the created exports
+        #@ are passed on to all the various child processes and child-shells of Jovian.
+        #@ 
+        #@ # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
+
+
+    touch "${HOME}"/.jovianrc
+    cat << EOF >> "${HOME}"/.jovianrc
+export -f conda
+export -f __conda_activate
+export -f __conda_reactivate
+export -f __conda_hashr
+export -f __add_sys_prefix_to_path
+EOF
+
 fi
